### PR TITLE
Document CustomCard

### PR DESCRIPTION
**Pull request by Abzol**
Adds missing documentation for custom object type CustomCard

### CODE REVIEW

**Review by JoshDM — COMMENTED** [review]
This looks good design-wise, but I cannot verify the validity of the changes per the lua api.

**Comment by Abzol** [comment]
Admittedly I found this by guesswork and the fact that spawning an object using these methods worked exactly as you'd suppose in my case, but do you mean that they don't work for you?

**Comment by Benjamin-Dobell** [comment]
Thanks for this! I'll fill out the missing properties in a follow up commit.

**Comment by Benjamin-Dobell** [comment]
Good job. You already had all the properties that make sense.

_Technically_ it'll accept deck properties too (because a card is represented as a 1x1 deck), but those properties don't make any sense in the context of single card.

**Pull request merged**
